"""
This is a setup_macOS.py script generated by py2applet

Usage:
   python3 setup_macOS.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {"includes": ['calculations.py',
                        'charts.py',
                        'debug.py',
                        'error.py',
                        'main.py',
                        'print_data.py',
                        'setup_macOS.py',
                        'strings.py']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
